In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
cd ~/demres

/Users/zurfarosa/demres

In [4]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:97% !important; }</style>"))

In [7]:
pd.read_csv('data/raw_data/Extract_Therapy_001.txt',delimiter='\t').head(15)

,patid,eventdate,sysdate,consid,prodcode,staffid,textid,bnfcode,qty,ndd,numdays,numpacks,packtype,issueseq
0,57001,08/02/1989,08/03/1997,9457,807,0,4,4,50.0,2.0,0,0.0,0,0
1,57001,20/02/1989,08/03/1997,9458,2322,0,1236,231,300.0,60.0,0,0.0,6,0
2,57001,27/02/1989,08/03/1997,9447,2322,0,1457,231,300.0,0.0,0,0.0,6,0
3,57001,09/05/1989,08/03/1997,9448,44,0,2,102,30.0,0.0,0,0.0,0,0
4,57001,10/07/1989,08/03/1997,9459,79,0,26,2,10.0,4.0,0,0.0,6,0
5,57001,07/08/1989,08/03/1997,9449,1559,0,100079,185,50.0,0.0,0,0.0,0,0
6,57001,25/08/1989,08/03/1997,9460,1559,0,76,185,50.0,1.0,0,0.0,0,0
7,57001,21/09/1989,08/03/1997,9461,1559,0,100080,185,50.0,0.0,0,0.0,0,0
8,57001,10/11/1989,08/03/1997,9450,1559,9001,100081,185,100.0,0.0,0,0.0,0,0
9,57001,10/11/1989,08/03/1997,9450,2322,9001,1457,231,300.0,0.0,0,0.0,6,0
10,57001,09/07/1990,08/03/1997,9462,1559,6001,100080,185,50.0,0.0,0,0.0,0,0
11,57001,09/07/1990,08/03/1997,9462,1559,6001,143,185,100.0,3.0,0,0.0,0,0
12,57001,27/07/1990,08/03/1997,9451,1894,9001,112,33,1.0,3.0,0,0.0,4,0
13,57001,04/10/1990,08/03/1997,9463,1559,9001,143,185,100.0,3.0,0,0.0,0,0
14,57001,19/11/1990,08/03/1997,9445,1559,9001,143,185,100.0,3.0,0,0.0,0,0

In [10]:
pd.read_csv('data/raw_data/Extract_Referral_001.txt',delimiter='\t').head(5)

,patid,eventdate,sysdate,constype,consid,medcode,staffid,textid,source,nhsspec,fhsaspec,inpatient,attendance,urgency
0,57001,31/10/1994,09/03/1997,4,9455,3389,0,0,0,0,16,3,0,0
1,57001,28/07/1994,09/03/1997,4,9475,5717,0,0,0,0,16,3,0,0
2,57001,31/10/1994,09/03/1997,4,9455,3668,0,0,0,0,16,3,0,0
3,57001,09/12/2004,09/12/2004,4,9575,2906,9001,0,1,16,2,0,0,2
4,57001,19/09/2007,19/09/2007,4,9667,12479,113001,26,1,0,2,3,0,4

In [5]:
pd.read_csv('data/pt_data/Extract_Practice_001.txt',delimiter='\t').head(10)

   pracid  region         lcd         uts
0       1       8  21/05/2013  07/09/1999
1       2      13  09/05/2013  16/03/2000
2       3       8  23/05/2013  06/09/2001
3       4      11  08/04/2013  07/01/1991
4       5       6  02/09/2010  27/03/1995
5       6       7  20/04/2013  18/11/1989
6       7       2  05/03/2002  22/08/1989
7       8      12  08/03/2002  31/08/1990
8       9      12  05/05/2009  08/08/2000
9      10       9  07/05/2013  09/01/2007

In [ ]:
pts = pd.read_csv('data/raw_data/Extract_Patient_001.txt',delimiter='\t')

In [ ]:
len(pts)

In [12]:
pts

,patid,vmid,gender,yob,mob,marital,famnum,chsreg,chsdate,prescr,capsup,ses,frd,crd,regstat,reggap,internal,tod,toreason,deathdate,accept
0,57001,1682,1,132,0,2,730,2,NaN,0,4,0,10/05/1977,10/05/1977,0,0,0,NaN,0,NaN,1
1,60001,3405,1,124,0,6,1475,2,NaN,4,4,0,11/03/1988,11/03/1988,0,0,0,NaN,0,NaN,1
2,149001,3238,2,119,0,6,1398,2,NaN,3,4,0,28/04/1978,28/04/1978,0,0,0,15/10/2004,2,NaN,1
3,364001,13436,2,137,0,2,6628,2,NaN,0,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
4,432001,4006,2,120,0,6,1726,2,NaN,3,4,0,05/11/1979,05/11/1979,0,0,0,NaN,0,NaN,1
5,519001,2697,2,127,0,6,1169,2,NaN,3,4,0,11/03/1988,11/03/1988,0,0,0,NaN,0,NaN,1
6,543001,18952,1,140,0,9,9586,2,NaN,0,4,0,26/10/1993,26/10/1993,0,0,0,11/05/2006,27,NaN,1
7,558001,6221,2,137,0,6,10580,2,NaN,0,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
8,644001,9164,2,135,0,6,5462,2,NaN,0,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
9,663001,3049,2,118,0,6,2639,2,NaN,3,4,0,11/03/1988,11/03/1988,0,0,0,NaN,0,NaN,1
10,676001,6667,2,130,0,6,2801,2,NaN,0,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
11,702001,10091,2,122,0,6,4164,2,NaN,3,4,0,11/03/1988,11/03/1988,0,0,0,09/05/2006,27,NaN,1
12,718001,6765,1,122,0,6,2840,2,NaN,4,4,0,30/03/1991,30/03/1991,0,0,0,13/02/2013,1,10/02/2013,1
13,746001,12138,2,127,0,6,3213,2,NaN,3,4,0,23/06/1988,23/06/1988,0,0,0,04/08/2008,1,14/07/2008,1
14,774001,20989,1,129,0,2,10469,2,NaN,4,4,0,08/08/1995,08/08/1995,0,0,0,NaN,0,NaN,1
15,802001,13315,2,124,0,3,6553,2,NaN,3,4,0,30/03/1991,30/03/1991,0,0,0,26/02/2007,27,NaN,1
16,803001,4641,1,123,0,6,1980,2,NaN,4,4,0,30/03/1991,30/03/1991,0,0,0,19/03/2012,27,NaN,1
17,819001,9824,1,127,0,6,4062,2,NaN,0,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
18,821001,8451,1,122,0,6,9375,2,NaN,4,4,0,11/03/1988,11/03/1988,0,0,0,NaN,0,NaN,1
19,830001,2919,2,121,0,6,1261,2,NaN,3,4,0,03/03/1975,03/03/1975,0,0,0,12/04/2006,27,NaN,1
20,853001,12141,1,120,0,6,141,2,NaN,4,4,0,23/06/1988,23/06/1988,0,0,0,NaN,0,NaN,1
21,960001,12476,2,119,0,2,5986,2,NaN,3,4,0,06/09/1988,06/09/1988,0,0,0,24/04/2008,1,22/04/2008,1
22,1064001,1972,2,128,0,6,858,2,NaN,3,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
23,1142001,4698,2,117,0,6,1999,2,NaN,3,4,0,07/04/1970,07/04/1970,0,0,0,26/04/2007,1,07/04/2007,1
24,1252001,3368,2,128,0,6,1456,2,NaN,3,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
25,1604001,18426,2,120,0,3,9348,2,NaN,3,4,0,08/06/1993,19/11/1998,1,573,0,19/10/2005,27,NaN,1
26,1645001,6280,1,129,0,6,2637,2,NaN,0,4,0,30/03/1991,30/03/1991,0,0,0,NaN,0,NaN,1
27,1670001,10181,2,126,0,6,4201,2,NaN,3,4,0,30/03/1991,30/03/1991,0,0,0,17/01/2006,2,NaN,1
28,1791001,10392,2,118,0,6,4319,2,NaN,3,4,0,30/03/1991,30/03/1991,0,0,0,28/11/2012,1,12/11/2012,1
29,1939001,6294,1,127,0,6,6876,2,NaN,0,4,0,11/03/1988,11/03/1988,0,0,0,NaN,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95296,6787675,8249,2,128,0,6,205,2,NaN,0,0,0,15/05/1967,15/05/1967,0,0,0,13/04/2011,3,NaN,1
95297,6826675,10031,2,121,0,6,3206,2,NaN,0,0,0,02/10/1989,02/10/1989,0,0,0,NaN,0,NaN,1
95298,7037675,10055,2,121,0,6,3405,2,NaN,0,0,0,02/10/1989,02/10/1989,0,0,0,NaN,0,NaN,1
95299,7405675,8343,2,138,0,6,679,2,NaN,0,0,0,02/12/1996,02/12/1996,0,0,0,NaN,0,NaN,1
95300,7411675,2062,1,129,0,6,1153,2,NaN,0,0,0,02/12/1996,02/12/1996,0,0,0,25/04/2012,1,24/04/2012,1
95301,7534675,10134,2,123,0,6,2444,2,NaN,0,0,0,02/10/1989,02/10/1989,0,0,0,06/01/2012,1,01/01/2012,1
95302,7728675,10183,2,130,0,6,3753,2,NaN,0,0,0,02/10/1989,02/10/1989,0,0,0,11/05/2012,1,09/05/2012,1
95303,7834675,2117,1,137,0,6,2218,2,NaN,0,0,0,23/01/1967,23/01/1967,0,0,0,NaN,0,NaN,1
95304,7853675,975,1,136,0,6,1897,2,NaN,0,0,0,01/10/1990,01/10/1990,0,0,0,NaN,0,NaN,1
95305,7860675,11523,2,112,0,6,171,2,NaN,0,0,0,04/09/1995,04/09/1995,0,0,0,25/09/2009,13,NaN,1
95306,7934675,979,1,124,0,6,3199,2,NaN,0,0,0,14/11/1960,14/11/1960,0,0,0,NaN,0,NaN,1
95307,8129675,1012,1,123,0,6,3841,2,NaN,0,0,0,01/10/1990,01/10/1990,0,0,0,17/04/2012,1,14/04/2012,1
95308,8130675,3923,1,112,0,6,202,2,NaN,0,0,0,02/10/1989,02/10/1989,0,0,0,03/03/2009,27,NaN,1
95309,8234675,10921,2,121,0,6,3861,2,NaN,0,0,0,23/11/1992,23/11/1992,0,0,0,01/11/2007,27,NaN,1
95310,8251675,8441,2,133,0,6,1372,2,NaN,0,0,0,09/04/1962,09/04/1962,0,0,0,NaN,0,NaN,1
95311,8430675,4001,1,128,0,6,2616,2,NaN,0,0,0,02/10/1989,02/10/1989,0,0,0,06/03/2012,1,05/03/2012,1
95312,8440675,1048,1,122,0,6,3075,2,NaN,0,0,0,12/06/1961,12/06/1961,0,0,0,NaN,0,NaN,1
95313,8597675,0,2,121,0,0,4012,2,NaN,3,0,0,14/01/2000,14/01/2000,0,0,0,01/04/2009,27,NaN,1
95314,8757675,0,2,128,0,0,4091,2,NaN,3,0,0,28/03/2000,28/03/2000,0,0,0,01/01/2010,13,NaN,1
95315,9381675,0,2,137,0,0,2216,2,NaN,3,0,0,23/02/2001,23/02/2001,0,0,0,NaN,0,NaN,1
95316,9829675,0,1,131,0,0,4547,2,NaN,4,0,0,26/09/2001,26/09/2001,0,0,0,NaN,0,NaN,1
95317,10220675,0,2,132,0,0,4706,2,NaN,3,0,0,01/05/2002,01/05/2002,0,0,0,13/07/2009,27,NaN,1
95318,10259675,0,2,119,0,0,4727,2,NaN,3,0,0,13/05/2002,13/05/2002,0,0,0,03/12/2008,27,NaN,1
95319,10417675,0,2,122,0,3,4718,2,NaN,3,0,0,12/06/2003,12/06/2003,0,0,0,NaN,0,NaN,1
95320,10526675,0,2,120,0,0,4849,2,NaN,3,0,0,29/08/2002,29/08/2002,0,0,0,03/12/2012,1,02/12/2012,1
95321,11194675,0,1,119,0,0,1004,2,NaN,19,0,0,20/03/2003,20/03/2003,0,0,0,09/01/2008,1,04/01/2008,1
95322,11265675,0,2,125,0,0,5159,2,NaN,19,0,0,22/04/2003,22/04/2003,0,0,0,19/07/2012,1,19/07/2012,1
95323,11503675,0,2,129,0,0,5252,2,NaN,19,0,0,12/08/2003,12/08/2003,0,0,0,30/10/2008,1,23/10/2008,1
95324,11617675,0,2,124,0,0,5295,2,NaN,19,0,0,01/10/2003,01/10/2003,0,0,0,29/01/2008,1,26/01/2008,1
95325,12742675,0,2,113,0,0,5610,2,NaN,19,0,0,26/01/2006,26/01/2006,0,0,0,20/02/2012,1,15/02/2012,1

In [ ]:
pd.read_csv('data/pt_data/Extract_Immunisation_001.txt',delimiter='\t').head(3)

In [8]:
pd.read_csv('data/pt_data/Extract_Consultation_001.txt',delimiter='\t').head(5)

   patid   eventdate     sysdate  constype  consid  staffid  duration
0  57001  11/06/1991  07/03/1997        15    9444     9001         0
1  57001  19/11/1990  07/03/1997         9    9445     9001         0
2  57001  01/01/1986  07/03/1997        15    9446        0         0
3  57001  27/02/1989  07/03/1997         9    9447     9001         0
4  57001  09/05/1989  07/03/1997         9    9448     9001         0

In [9]:
pd.read_csv('data/pt_data/Extract_Clinical_001.txt',delimiter='\t').head(5)

,patid,eventdate,sysdate,constype,consid,medcode,staffid,textid,episode,enttype,adid
0,57001,31/10/1994,09/03/1997,4,9455,3550,9001,0,0,26,1690
1,57001,31/10/1994,09/03/1997,5,9455,9897,9001,0,0,65,1691
2,57001,28/01/1993,09/03/1997,2,9474,4447,0,0,0,5,1692
3,57001,28/01/1993,09/03/1997,2,9474,3,0,0,0,14,1693
4,57001,28/01/1993,09/03/1997,2,9474,60,0,0,0,4,1694

medcode n

In [10]:
pd.read_csv('data/pt_data/Extract_Additional_001.txt',delimiter='\t').head(5)

   patid  enttype  adid  data1  data2  data3  data4  data5  data6  data7
0  57001       26  1690   1.00    NaN    NaN    NaN    NaN    NaN    NaN
1  57001       65  1691   0.00    NaN    NaN    NaN    NaN    NaN    NaN
2  57001        5  1692   2.00    NaN    0.0    0.0    NaN    NaN    NaN
3  57001       14  1693   1.22    0.0    NaN    NaN    NaN    NaN    NaN
4  57001        4  1694   2.00    NaN    NaN    NaN    0.0    0.0    NaN

In [11]:
pd.read_csv('data/pt_data/Extract_Additional_001.txt',delimiter='\t').head(5)

   patid  enttype  adid  data1  data2  data3  data4  data5  data6  data7
0  57001       26  1690   1.00    NaN    NaN    NaN    NaN    NaN    NaN
1  57001       65  1691   0.00    NaN    NaN    NaN    NaN    NaN    NaN
2  57001        5  1692   2.00    NaN    0.0    0.0    NaN    NaN    NaN
3  57001       14  1693   1.22    0.0    NaN    NaN    NaN    NaN    NaN
4  57001        4  1694   2.00    NaN    NaN    NaN    0.0    0.0    NaN

In [16]:
pd.read_csv('data/pt_data/Matching_File.txt',delimiter='\t').head(5)

,case_patid,case_pracid,case_gender,case_birthyear,case_index,match,control_patid,control_pracid,control_gender,control_birthyear,control_start,control_end
0,4923328,328,2,1916,01/07/2003,1,4355328,328,2,1916,01/01/2000,07/02/2009
1,1959216,216,1,1933,25/02/2011,1,6290216,216,1,1933,01/01/2000,01/06/2012
2,9271420,420,1,1917,20/06/2003,1,2770420,420,1,1917,02/01/2003,29/12/2009
3,548429,429,2,1925,11/05/2005,1,5473429,429,2,1925,01/01/2000,01/06/2012
4,14185081,81,2,1917,28/02/2005,1,5951081,81,2,1917,01/01/2000,27/01/2007

pd.read_csv('data/pt_data/Case_file.txt',delimiter='\t').head(5)

In [8]:
df = pd.read_csv('data/dicts/raw_pegasus_medical.txt',delimiter='\t',encoding='latin-1',header=None)
# df[df[3].str.contains('Zopiclone',na=False)][:10]
# note the importance of specifiying the encoding

CParserError: Error tokenizing data. C error: Expected 4 fields in line 2, saw 8

*medcode* is CRPD's version of the Read codes

In [10]:
pd.options.display.max_rows = 5000

In [11]:
pegmed = pd.read_csv('~/demres/data/dicts/proc_pegasus_medical.csv',delimiter=',')

In [12]:
pegmed[pegmed['read term'].str.contains('sleep|insomn|noctur|night',na=False,case=False)].sort_values

,medcode,readcode,clinical events,immunisation events,referral events,test events,read term,database build
108,16862,E274A00,41,0,1,0,Sleep drunkenness,February 2009
714,22081,Z1M..00,64,0,2,0,Sleep and rest interventions,February 2009
750,2129,E274900,11591,0,941,0,Nightmares,February 2009
3682,31167,66YP.00,18211,0,0,0,Asthma night-time symptoms,February 2009
4693,63591,U165200,4,0,0,0,[X]Exposr ignit/melt nightwear occ sch oth ins...,February 2009
6372,13173,663O.00,127337,0,1,1,Asthma not disturbing sleep,February 2009
6710,20748,H5B0.00,888,0,16,0,Obstructive sleep apnoea,February 2009
6763,54458,R005800,26,0,0,0,[D]Sleep dysfunction with sleep stage disturbance,February 2009
6955,66293,982..14,19,0,0,0,Night visit fee claim,February 2009
6956,2312,982..13,173724,0,569,6,Night visit administration,February 2009
6958,70798,982..11,1390,0,0,0,Higher rate FP81 night visit,February 2009
7366,11721,E274700,3643,0,340,0,Somnambulism - sleep walking,February 2009
7386,48539,R005100,91,0,2,0,[D]Insomnia with sleep apnoea,February 2009
7759,55395,U202.11,59,0,0,0,[X]Overdose - sleeping tabs,February 2009
7995,7819,E274.00,38979,0,572,0,Non-organic sleep disorders,February 2009
8073,15732,R005600,292,0,1,0,[D]Sleep rhythm irregular,February 2009
9035,21032,Eu51z11,107,0,1,0,[X]Emotional sleep disorder NOS,February 2009
9405,65355,43Vh.00,3,0,1,19,Paroxysmal nocturnal haemoglobinuria cell mark...,February 2009
9667,71628,F486z00,5,0,0,0,Night blindness NOS,February 2009
9814,99720,9b0X.00,26,0,0,0,Night visit local rota note,June 2010
10126,104942,38D0.00,2,0,0,0,Pittsburgh sleep quality index,September 2012
10704,35612,D112100,240,0,9,0,Paroxysmal nocturnal haemoglobinuria,February 2009
11292,25271,9827.00,15326,0,0,0,Night visit claimable - lower,February 2009
11732,103612,66Ys.00,2346,0,0,0,Asthma never causes night symptoms,January 2012
12105,19514,E274D11,648,0,18,0,Restless sleep,February 2009
12266,62925,Eu51y00,4,0,0,0,[X]Other nonorganic sleep disorders,February 2009
12670,95887,8HTn.00,1657,0,4712,0,Referral to sleep clinic,February 2009
13385,12072,8Q0..00,3455,0,110,0,Sleep management,February 2009
13395,2329,Fy0..00,66577,0,2211,6,Sleep disorders,February 2009
14218,6943,Eu51300,1260,0,86,0,[X]Sleepwalking,February 2009
14529,25604,T163.00,75,0,1,0,MVTA - motor vehicle out of control - driver f...,February 2009
15359,38686,Fy04.00,86,0,5,0,Sleep-related respiratory failure,February 2009
15500,51808,0AB2.00,22,0,0,0,Night porter,February 2009
16054,39990,E274B00,98,0,1,0,Repeated rapid eye movement sleep interruptions,February 2009
16732,43098,E274y00,45,0,0,0,Other non-organic sleep disorder,February 2009
17096,15407,R005z00,997,0,18,0,[D]Sleep dysfunction NOS,February 2009
17111,5675,1B1B100,726,0,4,0,Middle insomnia,February 2009
18829,4597,1B1B200,4208,0,24,1,Late insomnia,February 2009
20183,20438,R005312,258,0,60,0,[D]Syndrome sleep apnoea,February 2009
20185,2506,R005311,26210,0,7720,1,[D]Sleep apnoea syndrome,February 2009
21103,46445,U1A2.11,16,0,0,0,[X]Accidental poisoning with sleeping tablets,February 2009
21704,93615,9Nk0.00,3996,0,24,0,Seen in sleep clinic,February 2009
21714,8997,Fy02.00,524,0,11,0,Disorders of the sleep-wake schedule,February 2009
22658,32056,982C.00,5848,0,0,0,Night visit paid-higher rate,February 2009
23487,16434,E274000,72,0,3,0,Unspecified non-organic sleep disorder,February 2009
23541,1244,R005000,61853,0,1300,0,"[D]Sleep disturbance, unspecified",February 2009
23681,43547,246a.00,525,0,0,0,Average night interval diastolic blood pressure,February 2009
23827,17528,1B1R.00,17218,0,5,0,Good sleep pattern,February 2009
24139,47418,U607z12,19,0,0,0,[X] Adverse reaction to sleeping pill NOS,February 2009
24221,99442,98CX.00,5,0,0,0,GMS4 claim - night consultation paid,May 2010
24490,13135,1718.00,443435,0,4,0,Night cough absent,February 2009
24685,34148,67IT.00,3533,0,3,0,Advice to carer regarding child's sleep,February 2009
25489,27649,E274z00,77,0,3,0,Non-organic sleep disorder NOS,February 2009
26598,106745,42hF.00,2,0,0,0,Paroxysmal nocturnal haemoglobinuria screening...,August 2013
27007,2213,1A22000,55789,0,3643,56,Nocturnal enuresis,February 2009
27086,43524,44JG.00,11,0,0,262,Overnight albumin excretion rate,February 2009
27416,29288,SL7z.11,533,0,13,0,Sleeping drug poisoning,February 2009
28347,99537,98BL.00,1,0,0,0,GMS3 claim night consultation paid,May 2010
28413,71578,98BJ.00,1,0,0,0,GMS3 claim - night consultation signed,February 2009
28486,22819,Eu51z00,14,0,0,0,"[X]Nonorganic sleep disorder, unspecified",February 2009
30061,38143,663O000,79953,0,0,0,Asthma never disturbs sleep,February 2009
31037,36550,9823.00,15671,0,125,0,Night visit unsp.- claimable,February 2009
31141,4836,173B.00,187677,0,1707,3,Nocturnal cough / wheeze,February 2009
31740,48783,E274D00,27,0,0,0,Repetitive intrusions of sleep,February 2009
31749,28473,A86..11,231,0,13,0,Sleeping sickness,February 2009
32204,72536,9b0V.00,10,0,0,0,Night visit practice note,February 2009
32410,55179,E274C00,16,0,0,0,Other sleep stage or arousal dysfunction,February 2009
32610,45511,982A.00,13299,0,1,0,Night visit claimable - higher,February 2009
32929,38637,Z6GB600,75,0,18,0,Night splinting,February 2009
34785,18294,13JO.11,712,0,0,0,Night shift worker,February 2009
36587,64498,ZV75312,10,0,0,0,[V]Screening for sleeping sickness,February 2009
36632,101921,8G99.00,3,0,1,0,Sleep restriction therapy,March 2011
38776,5921,Fy00.00,55901,0,740,0,Disorders of initiating and maintaining sleep,February 2009
39721,49601,Fy05.00,22,0,0,0,Nocturnal sleep-related eating disorder,February 2009
39882,96694,T163000,1,0,0,0,MVTA-driver fell asleep - motor vehicle driver...,April 2009
40015,15515,E274100,5018,0,10,0,Transient insomnia,February 2009
40100,36301,R005300,692,0,58,0,[D]Hypersomnia with sleep apnoea,February 2009
40161,98249,F486000,1,0,0,0,Unspecified night blindness,December 2009
41755,39570,663r.00,15269,0,0,0,Asthma causes night symptoms 1 to 2 times per ...,February 2009
42089,72528,745A200,506,0,1,0,Overnight oximetry,February 2009
42685,93351,T76E.00,1,0,0,0,"Place of occurrence of accident or poisoning, ...",February 2009
42689,102216,4Q22100,0,0,0,2,Midnight cortisol level,May 2011
42916,62100,982..12,6800,0,0,0,Lower rate FP81 night visit,February 2009
43332,8148,Fy03.11,18612,0,1019,0,Obstructive sleep apnoea,February 2009
43676,100177,38Da.00,44,0,3,0,Berlin questionnaire for sleep apnoea,July 2010
43794,15767,8D73.00,163,0,9,0,Nocturnal bladder warning syst,February 2009
46505,24894,Eu51.00,435,0,9,0,[X]Nonorganic sleep disorders,February 2009
46662,45771,66Yh.00,889,0,0,0,Chronic obstructive pulmonary disease does not...,February 2009
47171,44305,Eu51500,202,0,5,0,[X]Nightmares,February 2009
47755,8084,R005.00,188663,0,405,0,[D]Sleep disturbances,February 2009
48259,38278,246b.00,719,0,0,0,Average night interval systolic blood pressure,February 2009
49117,750,R005200,587291,0,3187,2,[D]Insomnia NOS,February 2009
49837,37448,TJ7z000,46,0,1,0,Adverse reaction to sleeping pill NOS,February 2009
50733,15283,K5A2100,219,0,1,0,Menopausal sleeplessness,February 2009
51085,71920,0A94.00,3,0,0,0,Sleeping-car attendant,February 2009
51864,4559,3148.00,12373,0,1503,0,Sleep studies,February 2009
51897,26871,Q318.00,212,0,69,0,Primary sleep apnoea of newborn,February 2009
52334,6434,1736.00,10067,0,523,0,Paroxysmal nocturnal dyspnoea,February 2009
53232,96946,R008400,2468,0,63,0,[D]Night sweats,June 2009
53239,56151,U165.00,2,0,0,0,[X]Exposure to ignition or melting of nightwear,February 2009
54168,60806,1BX2.00,1509,0,2,0,Sleeping pattern,February 2009
54230,42847,1BX0.00,1450,0,0,0,Delayed onset of sleep,February 2009
54868,25794,1DA3.00,3755,0,0,0,Symptom occurs at night,February 2009
55249,38146,663N100,6673,0,0,0,Asthma disturbs sleep weekly,February 2009
56585,16115,E274200,1354,0,10,0,Persistent insomnia,February 2009
56774,93855,9b0W.00,250,0,0,0,"Night visit, deputising service note",February 2009
57948,30742,F13z500,217,0,1,0,Benign neonatal sleep myoclonus,February 2009
59140,102181,4Q22000,0,0,0,3,Post overnight dexamethasone cortisol level,April 2011
61451,7543,9NF5.00,408559,0,28,0,"Out of hours, not night visit",February 2009
62077,23779,H5B..00,2021,0,197,0,Sleep apnoea,February 2009
62734,71178,8C1I.00,8,0,0,0,Putting patient to bed at night,February 2009
63062,7603,Fy03.00,12719,0,2057,0,Sleep apnoea,February 2009
63914,51397,ZV1B100,21,0,1,0,[V]Personal history of unhealthy sleep-wake sc...,February 2009
64562,36745,E274F00,28,0,0,0,Inversion of sleep rhythm,February 2009
65047,18116,173D.00,2256,0,106,1,Nocturnal dyspnoea,February 2009
65205,16447,R005500,233,0,3,0,[D]Sleep rhythm inversion,February 2009
66111,72880,9b0U.00,119,0,0,0,Night visit note,February 2009
67233,31236,R005.12,403,0,0,0,[D]Sleep rhythm problems,February 2009
67234,10349,R005.11,7563,0,44,0,[D]Insomnia - symptom,February 2009
68488,71605,98BK.00,519,0,0,0,GMS3 claim - night consultation sent to HA,February 2009
69925,56853,U165600,1,0,0,0,[X]Exposur ignitn/melting nightwear occ indust...,February 2009
70498,18125,G330000,223,0,11,0,Nocturnal angina,February 2009
70995,103449,1F9C.00,12,0,0,0,Eats at night,December 2011
71187,60974,1BX9.00,19,0,0,0,Light sleep,February 2009
71373,30815,663N000,13994,0,0,0,Asthma causing night waking,February 2009
71636,30626,Eu51000,2458,0,4,0,[X]Nonorganic insomnia,February 2009
71770,53912,Fyu5800,39,0,1,0,[X]Other sleep disorders,February 2009
72892,100412,F486200,1,0,0,0,Hereditary night blindness NOS,August 2010
73716,5579,R084200,7838,0,198,1,[D]Nocturia,February 2009
74701,47745,E274600,59,0,0,0,Shifting sleep-work schedule,February 2009
75660,66959,98CW.00,983,0,0,0,GMS4 claim - night consultation sent to HA,February 2009
77228,10989,1BX..00,3382,0,88,0,Sleep observations,February 2009
78151,32987,E274E00,95,0,0,0,'Short-sleeper',February 2009
78177,25211,1BX1.00,2175,0,38,0,Excessive sleep,February 2009
78683,25270,982..00,37951,0,22,0,FP81 - night visit claim,February 2009
79240,840,1A13.00,176456,0,12106,59,Nocturia,February 2009
79429,8853,Eu51400,86,0,3,0,[X]Sleep terrors,February 2009
80421,4537,1B1B.11,449676,0,2211,0,C/O - insomnia,February 2009
80444,9536,1B1D.11,8673,0,350,0,Nightmares - symptom,February 2009
81675,40637,F486300,25,0,0,0,Congenital night blindness NOS,February 2009
83401,56809,7065800,303,0,16,0,Sleep studies,February 2009
84627,101729,Eu51213,1,0,0,0,[X]Psychogenic inversion of sleep rhythm,February 2011
84693,99106,ZV6A.00,4,0,0,0,[V]First in a series of regular day or night a...,April 2010
84909,101913,Z1M1.00,9,0,0,0,Disturbing sleep,March 2011
87854,25003,F486.00,315,0,35,0,Night blindness,February 2009
88501,7416,663N.00,43757,0,15,0,Asthma disturbing sleep,February 2009
89159,4766,N247111,66058,0,240,0,Night cramps,February 2009
89272,106862,8O1A.00,2,0,0,0,Provision of night time positioning aid,August 2013
90109,102400,66Yq.00,5292,0,0,0,Asthma causes night time symptoms 1 to 2 times...,June 2011
90556,8913,E274800,8053,0,556,0,Night terrors,February 2009
91919,102395,66Yr.00,5045,0,1,0,Asthma causes symptoms most nights,June 2011
92093,45770,66Yg.00,304,0,9,0,Chronic obstructive pulmonary disease disturbs...,February 2009
92384,85670,7065A00,548,0,24,0,Sleep studies NEC,February 2009
92527,72631,98CV.00,147,0,0,0,GMS4 claim - night consultation signed,February 2009
92641,94508,1BN2.00,31,0,0,0,Wanders during the day and at night,February 2009
92751,3523,1B1B000,3875,0,21,0,Initial insomnia,February 2009
93752,30385,1BN1.00,424,0,13,0,Wanders at night,February 2009
94457,99834,R003400,344,0,18,0,[D]Nocturnal seizure,June 2010
94784,4023,E274111,117094,0,506,0,Insomnia NOS,February 2009
94915,57515,U165300,1,0,0,0,[X]Exposur to ignitn/meltng nightwear occ spor...,February 2009
94947,26546,E274.12,169,0,0,0,Insomnia due to nonorganic sleep disorder,February 2009
96971,7725,1B1Q.00,91558,0,1008,0,Poor sleep pattern,February 2009
97028,13175,663N200,7459,0,1,0,Asthma disturbs sleep frequently,February 2009
97123,41737,R005900,34,0,0,0,[D]Sleep dysfunction with arousal disturbance,February 2009
98495,58911,R005700,20,0,1,0,[D]Sleep-wake rhythm non-24-hour cycle,February 2009
98555,101313,F486400,1,0,0,0,Acquired night blindness,January 2011
99251,61111,9824.00,14453,0,4,0,Night visit - not claimable,February 2009
99771,1740,1662.12,54993,0,3755,28,Night sweats,February 2009
99987,3068,1717.00,1207974,0,636,2,Night cough present,February 2009
100756,21305,1B1B.00,51359,0,166,0,Cannot sleep - insomnia,February 2009
100786,15387,1B1D.00,415,0,10,0,C/O nightmares,February 2009
100961,46759,8H32.00,1637,0,10,0,Night hospital care,February 2009
101995,98268,38D1.00,6,0,0,0,Insomnia severity index,December 2009
102187,4602,667B.00,2103,0,146,0,Nocturnal epilepsy,February 2009
103348,66943,C245.00,5,0,2,0,Vitamin A deficiency with night blindness,February 2009
104180,67187,13FM.00,27,0,0,0,Sleeping in night shelter,February 2009
104296,104005,9b9Y.00,5,0,1,0,Sleep studies - specialty,May 2012
105413,23923,Eu51200,37,0,1,0,[X]Nonorganic disorder of the sleep-wake schedule,February 2009
105864,96037,8G9B.00,1345,0,1,0,Sleep hygiene behaviour education,February 2009
106115,32241,982B.00,3641,0,0,0,Night visit paid-lower rate,February 2009